version: '3.8'
services:
  development:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
    - development:/var/lib/postgresql/data
volumes:
  development:
    driver: local